<a href="https://colab.research.google.com/github/rifatentr/Data-Mining/blob/1028---Trailing-Zeroes-(I)-to-1028---Trailing-Zeroes-(I)/DM_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
weather=pd.read_csv("/content/weatherHistory.csv")
weather

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
12295,2007-01-05 07:00:00.000 +0100,Overcast,rain,2.466667,-0.122222,0.99,9.0965,202.0,5.5384,0.0,1018.42,Mostly cloudy until night.
12296,2007-01-05 08:00:00.000 +0100,Partly Cloudy,rain,2.316667,-0.377778,0.99,9.3863,204.0,4.2987,0.0,1018.41,Mostly cloudy until night.
12297,2007-01-05 09:00:00.000 +0100,Clear,rain,2.966667,0.905556,0.99,7.5187,177.0,4.7495,0.0,1019.08,Mostly cloudy until night.
12298,2007-01-05 10:00:00.000 +0100,Partly Cloudy,rain,5.927778,3.522222,0.87,11.3344,243.0,9.6278,0.0,1019.53,Mostly cloudy until night.
12299,2007-01-05 11:00:00.000 +0100,Partly Cloudy,rain,8.772222,6.500000,0.77,14.3612,251.0,9.9820,0.0,10.00,NaN

In [ ]:
weather.head(10)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
5,2006-04-01 05:00:00.000 +0200,Partly Cloudy,rain,9.222222,7.111111,0.85,13.9587,258.0,14.9569,0.0,1016.66,Partly cloudy throughout the day.
6,2006-04-01 06:00:00.000 +0200,Partly Cloudy,rain,7.733333,5.522222,0.95,12.3648,259.0,9.9820,0.0,1016.72,Partly cloudy throughout the day.
7,2006-04-01 07:00:00.000 +0200,Partly Cloudy,rain,8.772222,6.527778,0.89,14.1519,260.0,9.9820,0.0,1016.84,Partly cloudy throughout the day.
8,2006-04-01 08:00:00.000 +0200,Partly Cloudy,rain,10.822222,10.822222,0.82,11.3183,259.0,9.9820,0.0,1017.37,Partly cloudy throughout the day.
9,2006-04-01 09:00:00.000 +0200,Partly Cloudy,rain,13.772222,13.772222,0.72,12.5258,279.0,9.9820,0.0,1017.22,Partly cloudy throughout the day.

In [ ]:
import statistics

In [ ]:
mean=statistics.mean(weather["Humidity"])

print("Mean of Humidity is:", mean)

Mean of Humidity is: 0.751450406504065

In [ ]:
median=statistics.median(weather["Humidity"])

print("Median of Humidity is:", median)

Median of Humidity is: 0.8

In [ ]:
mode=statistics.mode(weather["Humidity"])

print("Mode of Humidity is:", mode)

Mode of Humidity is: 0.93

In [ ]:
stdev=statistics.stdev(weather["Humidity"])

print("Standard deviation of Humidity is:", stdev)

Standard deviation of Humidity is: 0.18452971998616596

In [ ]:
variance=statistics.variance(weather["Humidity"])

print("variance of Humidity is:", variance)

variance of Humidity is: 0.034051217558172815